-- 墨名堂 · 灵喵京 v0.1 数据库建表脚本
-- 在 Supabase SQL Editor 中粘贴运行即可

-- 用户表
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone VARCHAR(20) UNIQUE,
  password_hash VARCHAR(128) NOT NULL,
  nickname VARCHAR(50) NOT NULL DEFAULT '新喵客',
  tier VARCHAR(20) DEFAULT 'FUXIAO',
  total_meowcoin BIGINT DEFAULT 0,
  used_meowcoin BIGINT DEFAULT 0,
  frozen_meowcoin BIGINT DEFAULT 0,
  wu_jing BIGINT DEFAULT 0,
  public_tier VARCHAR(20),
  last_login_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 管理员
CREATE TABLE IF NOT EXISTS admin_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(64) UNIQUE NOT NULL,
  password_hash VARCHAR(128) NOT NULL,
  display_name VARCHAR(64) NOT NULL,
  role VARCHAR(32) DEFAULT 'EDITOR',
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 喵币流水
CREATE TABLE IF NOT EXISTS meowcoin_ledger (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id),
  direction VARCHAR(4) NOT NULL,
  type VARCHAR(32) NOT NULL,
  amount BIGINT NOT NULL,
  balance_before BIGINT NOT NULL,
  balance_after BIGINT NOT NULL,
  available_before BIGINT NOT NULL,
  available_after BIGINT NOT NULL,
  ref_type VARCHAR(32),
  ref_id VARCHAR(128),
  idempotency_key VARCHAR(128) UNIQUE,
  meta JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 平台绑定
CREATE TABLE IF NOT EXISTS platform_bindings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id),
  platform VARCHAR(32) NOT NULL,
  platform_user_id VARCHAR(128) NOT NULL,
  bound_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id, platform)
);

-- 平台订单
CREATE TABLE IF NOT EXISTS platform_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  platform VARCHAR(32) NOT NULL,
  shop_id VARCHAR(64),
  order_id VARCHAR(128) NOT NULL,
  user_id BIGINT REFERENCES users(id),
  paid_at TIMESTAMPTZ,
  status VARCHAR(32),
  order_remark VARCHAR(512),
  raw_amount BIGINT DEFAULT 0,
  valid_amount BIGINT DEFAULT 0,
  meowcoin_earned BIGINT DEFAULT 0,
  calc_status VARCHAR(20) DEFAULT 'PENDING',
  exclude_reason VARCHAR(64),
  items_json JSONB DEFAULT '[]',
  synced_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(platform, order_id)
);

-- 用户标签
CREATE TABLE IF NOT EXISTS user_tags (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(20) NOT NULL UNIQUE,
  color VARCHAR(7) DEFAULT '#6366F1',
  description VARCHAR(100),
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 用户标签关联
CREATE TABLE IF NOT EXISTS user_tag_assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
  tag_id BIGINT REFERENCES user_tags(id) ON DELETE CASCADE,
  assigned_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id, tag_id)
);

-- ========== 初始化种子数据 ==========

-- 密码: Test1234! (bcrypt)
INSERT INTO users (phone, password_hash, nickname, tier, total_meowcoin, used_meowcoin)
VALUES ('13800000001', '$2b$10$ml/5tMImHVGlAjxghT4QIe8hioIUd10/DngZQWBgJitSJ.raUxD56', '墨名堂·花间喵', 'BAIXIAO', 2500, 300)
ON CONFLICT (phone) DO NOTHING;

-- 管理员: admin / Admin123!
INSERT INTO admin_users (username, password_hash, display_name, role)
VALUES ('admin', '$2b$10$nv9RAL7p.mlP3hPNXC0J4eERn3vfxtYTHDyYkIXP5lnpnOUZ52T12', '掌事大人', 'SUPER_ADMIN')
ON CONFLICT (username) DO NOTHING;

-- 玄喵标签
INSERT INTO user_tags (name, color, description)
VALUES ('玄喵', '#1A1A2E', '隐藏阶位·邀请制，授予后用户自动切换为玄喵阶位')
ON CONFLICT (name) DO NOTHING;

-- Demo 流水（用户ID=1）
INSERT INTO meowcoin_ledger (user_id, direction, type, amount, balance_before, balance_after, available_before, available_after, ref_type, ref_id, idempotency_key, meta)
VALUES 
  (1, 'IN', 'ORDER_SYNC', 1200, 0, 1200, 0, 1200, 'ORDER', 'T20231001', 'seed-001', '{"platform":"淘宝","desc":"宋制旋裙"}'::jsonb),
  (1, 'IN', 'ORDER_SYNC', 800, 1200, 2000, 1200, 2000, 'ORDER', 'T20231115', 'seed-002', '{"platform":"淘宝","desc":"唐制齐胸"}'::jsonb),
  (1, 'IN', 'ORDER_SYNC', 500, 2000, 2500, 2000, 2500, 'ORDER', 'T20240320', 'seed-003', '{"platform":"抖音","desc":"明制披风"}'::jsonb)
ON CONFLICT (idempotency_key) DO NOTHING;

-- Demo 订单
INSERT INTO platform_orders (platform, order_id, user_id, paid_at, status, raw_amount, valid_amount, meowcoin_earned, calc_status, exclude_reason, items_json)
VALUES
  ('淘宝', 'T20231001', 1, '2023-01-15', 'TRADE_FINISHED', 120000, 120000, 1200, 'COUNTED', NULL, '[{"title":"宋制旋裙 真丝汉服","code":"H10001","amount":120000,"rule":"COUNTED_H"}]'::jsonb),
  ('淘宝', 'T20231115', 1, '2023-11-15', 'TRADE_FINISHED', 80000, 80000, 800, 'COUNTED', NULL, '[{"title":"唐制齐胸 真丝","code":"H10002","amount":80000,"rule":"COUNTED_H"}]'::jsonb),
  ('抖音', 'DY20240320', 1, '2024-03-20', 'TRADE_FINISHED', 50000, 50000, 500, 'COUNTED', NULL, '[{"title":"明制披风 真丝","code":"H20001","amount":50000,"rule":"COUNTED_H"}]'::jsonb),
  ('淘宝', 'T20240501', 1, '2024-05-01', 'TRADE_FINISHED', 9900, 0, 0, 'EXCLUDED', 'EXCLUDED_TITLE', '[{"title":"特价款 汉服体验","code":"H30001","amount":9900,"rule":"EXCLUDED_TITLE"}]'::jsonb)
ON CONFLICT (platform, order_id) DO NOTHING;
